swagger: "2.0"

info:
  version: "1.0"
  title: Tweet Scraper
  license:
    name: MIT

schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /hashtags/{hashtag}:
    get:
      tags:
        - "Tweet"
      parameters:
        - name: hashtag
          description: A hashtag by which tweets will be gotten.
          in: path
          type: string
          minLength: 1
          maxLength: 64
          pattern: '^\S{1,64}$'
          required: true
        - name: limit
          description: Maximum number of tweets in response.
          in: query
          type: integer
          minimum: 0
          maximum: 1000
          default: 30
          required: false
      responses:
        '200':
          description: 'Returns tweets by hashtag'
          schema:
            $ref: '#/definitions/Tweets'

      x-amazon-apigateway-integration:
        responses: {}
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HashtagTweetsLambda.Arn}/invocations
        httpMethod: "POST"
        type: "aws_proxy"
  /users/{username}:
    get:
      tags:
        - "Twitter"
      parameters:
        - name: username
          description: A username of twitter user by which tweets will be gotten.
          in: path
          type: string
          pattern: '^\S{1,64}$'
          minLength: 1
          maxLength: 64
          required: true
        - name: limit
          description: Maximum number of tweets in response.
          in: query
          type: integer
          minimum: 0
          maximum: 1000
          default: 30
          required: false
      responses:
        '200':
          description: 'User tweets'
          schema:
            $ref: '#/definitions/Tweets'

definitions:
  Account:
    type: object
    properties:
      fullname:
        type: string
      href:
        type: string
      id:
        type: integer

  Tweet:
    type: object
    properties:
      account:
        $ref: '#/definitions/Account'
      date:
        type: string
      hashtags:
        type: array
        items:
          type: string
      likes:
        type: integer
      replies:
        type: integer
      retweets:
        type: integer
      text:
        type: string

  Tweets:
    type: array
    items:
      $ref: '#/definitions/Tweet'